[package]
name = "cs_cityio_backend"
version = "0.1.0"
authors = ["yasushi"]
edition = "2018"

[dependencies]
actix-web= "1.0.0-alpha.4"
actix-files= "0.1.3"
actix-cors= "0.1.0"

bytes = "0.4"
futures = "0.1"
log = "0.4"
env_logger = "*"
url = "1.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"
postgres = {version = "0.15", features = ["with-serde_json"]}
base64="0.10.1"

sha256 = { path="../sha256" }
